### ISSUE TITLE
Script Fails to Run

### ISSUE THREAD

**Issue by marktyers** [ngchianglin/DenoWebRTCGroupChat#3]
The server no longer works with the latest version of Deno. Same error on MacOS11 and Ubuntu Server 18.04

```
$ deno --version
deno 1.8.3 (release, x86_64-unknown-linux-gnu)
v8 9.0.257.3
typescript 4.2.2

$ deno run --allow-all groupchat-server.ts
INFO server started 127.0.0.1:8000 Fri Apr 09 2021 16:02:12 GMT+0000 (GMT)
error: Uncaught (in promise) NotFound: No such file or directory (os error 2)
    at handleError (deno:core/core.js:186:12)
    at jsonOpParseResult (deno:core/core.js:356:9)
    at asyncHandle (deno:core/core.js:223:40)
    at Array.asyncHandlers.<computed> (deno:core/core.js:238:9)
    at handleAsyncMsgFromRust (deno:core/core.js:207:32)
```

**Comment by clemens-tolboom** [comment]
Have you tried `deno run --allow-net --allow-read=./pass/passwd,/dev/urandom groupchat-server.ts` as per README.md?

```
deno --version
deno 1.8.1 (release, x86_64-apple-darwin)
v8 9.0.257.3
typescript 4.2.2
```
After upgrading to 1.9.0 same working result
```
deno --version
deno 1.9.0 (release, x86_64-apple-darwin)
v8 9.1.269.5
typescript 4.2.2
```
## Result
```
deno run --allow-net --allow-read=./pass/passwd,/dev/urandom groupchat-server.ts
Check file:///Users/clemens/Sites/deno/DenoWebRTCGroupChat/signalserver/groupchat-server.ts
INFO server started 127.0.0.1:8000 Thu Apr 15 2021 10:51:06 GMT+0200 (Central European Summer Time)
INFO  
INFO -------------------------Statistics------------------------
INFO "2021-04-15T08:51:06.194Z"
INFO Server uptime: 15
INFO Number of sockets (num_sockets): 0
INFO Number of sockets before cleanup (socket_list): 0
INFO Number of stale sockets before cleanup (socket_list): 0
INFO Number of chat users: 0
INFO Number of accounts with failed login: 0
INFO Number of accounts locked: 0
INFO ------------------------------------------------------------
INFO  
```
